stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: Dockerfile
      buildContext: .
      tag: csp2-centos-1:5000/fiware-keyrock
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch: {}
      event: {}
  when:
    event: {}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./keyrock-deployment.yaml
  - applyYamlConfig:
      path: ./keyrock-service.yaml
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        apt-get install sshpass
        sshpass -p password ssh -tt -o StrictHostKeyChecking=no newuser@192.168.100.178 ./check_pod_status.sh p-kpggk-pipeline keyrock
    when:
      branch: {}
      event: {}
  when:
    event: {}
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |
        apt-get update
        echo Y | apt-get install npm
        npm -v
        sleep 300
        npm install -g newman
        newman run ./KeyRock.postman_collection.json
  when:
    branch:
      include:
      - master
    event:
      include:
      - pull_request
      - push
timeout: 300
notification: {}
