stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: Dockerfile
      buildContext: .
      tag: img_fiware-keyrock_v7.7.tar.gz :${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.0.8.61:31484
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      event: {}
  when:
    event: {}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: extras/docker/keyrock-deployment.yaml
  - applyYamlConfig:
      path: extras/docker/keyrock-service.yaml
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        apt-get install sshpass
        sshpass -p password ssh -tt -o StrictHostKeyChecking=no newuser@192.168.100.178 ./check_pod_status.sh p-kpggk-pipeline keyrock
  when:
    event: {}
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |+
        apt-get update
        echo Y | apt-get install npm
        npm -v
        npm install -g newman
        newman run http://192.168.100.178/csp_containerizationandautomation/keyrock/raw/master/KeyRock.postman_collection.json
  when:
    branch: {}
    event: {}

timeout: 300
notification: {}
