stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: Dockerfile
      buildContext: .
      tag: 172.30.76.49:5000/keyrock
      pushRemote: true
      registry: 172.30.76.49:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      event: {}
  when:
    event: {}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: extras/docker/keyrock-deployment.yaml
  - applyYamlConfig:
      path: extras/docker/keyrock-service.yaml
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        apt-get install sshpass
        sshpass -p password ssh -tt -o StrictHostKeyChecking=no newuser@192.168.100.178 ./check_pod_status.sh p-kpggk-pipeline keyrock
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  when:
    event:
      include:
      - pull_request
      - push
      - tag
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |
        apt-get update
        echo Y | apt-get install npm
        npm -v
        sleep 300
        npm install -g newman
        newman run ./KeyRock.postman_collection.json
  when:
    branch: {}
    event:
      include:
      - pull_request
      - push
      - tag
timeout: 300
notification: {}
